### ISSUE TITLE
Support multiple file types

### ISSUE THREAD

**Issue by ianks** [Shopify/smart_todo#31]
Hey, this gem is awesome! One thing we would love is the ability to use this on other filetypes, specifically typescript and scss. Is there currently a way to do this?

**Comment by Edouard-chin** [comment]
👋 Thanks for using this gem !

There is currently no way to run this tool on other programming languages other than ruby. However, I also had in mind to add support for other filetypes. I'll try to take some time soon to add this feature and I'll let you know !
