### ISSUE TITLE
Support running bin locally with no credentials

### ISSUE THREAD

**Issue by burke** [Shopify/smart_todo#32]
I have a CI failure due to smart_todo here: https://buildkite.com/shopify/dev/builds/13584#8c3ee7ca-e462-4f27-a38a-b6d951a562af

In order to debug this, the first thing I tried is to run `bin/smart_todo` locally, but it won't let me.

It would be really useful if it supported running locally without credentials, but just printing the triggered conditions.

**Comment by Edouard-chin** [comment]
Ack, thanks for the report.

I'll add a dry run options which will be the default if no credentials are given
