### ISSUE TITLE
sdhasdh

### ISSUE THREAD

**Issue by miguelsavard** [Shopify/smart_todo#73]
**Asynchronous Interaction Resources**

The JSA Program has been showing persistent performance concerns with async smiley since the channel has been introduced in the summer of 2023. Support advisors in Solstice have been greatly outperforming the JSA Program, and we need to create an action plan to increase the average quality of async interactions. Below are the commitments we made to help increase average async smiley in the JSA Program:

1. Create a list of stellar async interactions that our Junior Support Advisors can study
2. Focus our Q4 2023 homesite on how to bring _Surprise & Delight_ to our async interactions
3. Curate a small collection of courses and resources that can help up-skill our Junior Support Advisors on async interactions

**Comment by lavoiesl** [comment]
This appears to be off topic. Closing.
Please reopen and provide a meaningful title if you disagree.
